WITH trap_details AS (
    SELECT 
        DISTINCT
        FULL_ADDRESS, 
        ADDRESS_NUMBER, 
        FULL_ROAD_NAME, 
        TOWN_CITY, 
        TERRITORIAL_AUTHORITY,
        LATITUDE,
        LONGITUDE
    FROM {{ ref('int_trap_details') }}
)

SELECT 
    ROW_NUMBER() OVER(ORDER BY TERRITORIAL_AUTHORITY, TOWN_CITY, FULL_ROAD_NAME, ADDRESS_NUMBER, FULL_ADDRESS) AS TRAP_ADDRESS_ID,
    FULL_ADDRESS, 
    ADDRESS_NUMBER, 
    FULL_ROAD_NAME, 
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY,
    LATITUDE,
    LONGITUDE
FROM trap_details
ORDER BY TERRITORIAL_AUTHORITY, TOWN_CITY, FULL_ROAD_NAME, ADDRESS_NUMBER, FULL_ADDRESS

