{{
    config(materialized='view')
}}

SELECT TRAP_LOCATION_ID,
    TRAP_ADDRESS_ID,
    ACTIVITY_TYPE,
    INSTALLED_AT,
    UPLOADED_AT,
    STRIKE_AT,
    BATCH_ID,
    CREATED_BY,
    TRAP_ID,
    LATITUDE,
    LONGITUDE,
    BATTERY_LEVEL,
    DISTANCE_IN_METERS,
    -- INSTALLED
    CONCAT(YEAR(INSTALLED_AT::TIMESTAMP_LTZ), '-', TO_VARCHAR(MONTH(INSTALLED_AT::TIMESTAMP_LTZ), '00'), '-', TO_VARCHAR(DAYOFMONTH(INSTALLED_AT::TIMESTAMP_LTZ), '00')) AS INSTALLED_DATE,
    YEAR(INSTALLED_AT::TIMESTAMP_LTZ) AS INSTALLED_YEAR,
    MONTH(INSTALLED_AT::TIMESTAMP_LTZ) AS INSTALLED_MONTH,
    DAYOFMONTH(INSTALLED_AT::TIMESTAMP_LTZ) AS INSTALLED_DAY,
    HOUR(INSTALLED_AT::TIMESTAMP_LTZ) AS INSTALLED_HOUR,
    MINUTE(INSTALLED_AT::TIMESTAMP_LTZ) AS INSTALLED_MINUTE,
    SECOND(INSTALLED_AT::TIMESTAMP_LTZ) AS INSTALLED_SECOND,
    --UPLOADED
    CONCAT(YEAR(UPLOADED_AT::TIMESTAMP_LTZ), '-', TO_VARCHAR(MONTH(UPLOADED_AT::TIMESTAMP_LTZ), '00'), '-', TO_VARCHAR(DAYOFMONTH(UPLOADED_AT::TIMESTAMP_LTZ), '00')) AS UPLOADED_DATE,
    YEAR(UPLOADED_AT::TIMESTAMP_LTZ) AS UPLOADED_YEAR,
    MONTH(UPLOADED_AT::TIMESTAMP_LTZ) AS UPLOADED_MONTH,
    DAYOFMONTH(UPLOADED_AT::TIMESTAMP_LTZ) AS UPLOADED_DAY,
    HOUR(UPLOADED_AT::TIMESTAMP_LTZ) AS UPLOADED_HOUR,
    MINUTE(UPLOADED_AT::TIMESTAMP_LTZ) AS UPLOADED_MINUTE,
    SECOND(UPLOADED_AT::TIMESTAMP_LTZ) AS UPLOADED_SECOND,
    -- STRIKED
    CONCAT(YEAR(STRIKE_AT::TIMESTAMP_LTZ), '-', TO_VARCHAR(MONTH(STRIKE_AT::TIMESTAMP_LTZ), '00'), '-', TO_VARCHAR(DAYOFMONTH(STRIKE_AT::TIMESTAMP_LTZ), '00')) AS STRIKED_DATE,
    YEAR(STRIKE_AT::TIMESTAMP_LTZ) AS STRIKED_YEAR,
    MONTH(STRIKE_AT::TIMESTAMP_LTZ) AS STRIKED_MONTH,
    DAYOFMONTH(STRIKE_AT::TIMESTAMP_LTZ) AS STRIKED_DAY,
    HOUR(STRIKE_AT::TIMESTAMP_LTZ) AS STRIKED_HOUR,
    MINUTE(STRIKE_AT::TIMESTAMP_LTZ) AS STRIKED_MINUTE,
    SECOND(STRIKE_AT::TIMESTAMP_LTZ) AS STRIKED_SECOND,
    -- TIME SINCE INSTALLED
    TIMESTAMPDIFF(minute, STRIKE_AT::TIMESTAMP_LTZ, UPLOADED_AT::TIMESTAMP_LTZ) AS MINUTES_SINCE_INSTALLED
FROM {{ ref('dim_nz_trap_details') }}