WITH trap_data AS (
    SELECT 
        UPLOADED_AT, 
        ACTIVITY_TYPE, 
        STRIKE_AT, 
        BATCH_ID, 
        CREATED_BY, 
        TRAP_ID, 
        LATITUDE, 
        LONGITUDE, 
        BATTERY_LEVEL, 
        INSTALLED_AT
    FROM 
        {{ ref('stg_trap_data') }}
),

nz_trap_locations AS (
    SELECT
	LOCATION_ID,
	FULL_ADDRESS,
	ADDRESS_NUMBER,
	FULL_ROAD_NAME,
    SUBURB_LOCALITY,
	TOWN_CITY,
	TERRITORIAL_AUTHORITY,
	TRAP_LONGITUDE,
	TRAP_LATITUDE,
	ADDRESS_LONGITUDE,
	ADDRESS_LATITUDE,
	DISTANCE_IN_METERS
    FROM {{ ref('dim_nz_locations') }}
)

SELECT
    n.LOCATION_ID,
    n.FULL_ADDRESS,
    n.ADDRESS_NUMBER,
	n.FULL_ROAD_NAME,
    n.SUBURB_LOCALITY,
	n.TOWN_CITY,
	n.TERRITORIAL_AUTHORITY,
	n.TRAP_LONGITUDE,
	n.TRAP_LATITUDE,
	n.ADDRESS_LONGITUDE,
	n.ADDRESS_LATITUDE,
	n.DISTANCE_IN_METERS,
    t.UPLOADED_AT, 
    t.ACTIVITY_TYPE, 
    t.STRIKE_AT, 
    t.BATCH_ID, 
    t.CREATED_BY, 
    t.TRAP_ID, 
    t.LATITUDE, 
    t.LONGITUDE, 
    t.BATTERY_LEVEL, 
    t.INSTALLED_AT
FROM trap_data t
JOIN nz_trap_locations n 
ON n.TRAP_LONGITUDE = t.LONGITUDE 
AND n.TRAP_LATITUDE = t.LATITUDE
