SELECT 
    STRIKED_DATE, 
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY, 
    SUM(NUM_KILLS) AS NUM_KILLS, 
    STRIKED_DAY,
    STRIKED_MONTH,
    STRIKED_YEAR
FROM {{ ref('nz_daily_kills') }} 
GROUP BY STRIKED_DATE, 
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY, 
    STRIKED_DAY,
    STRIKED_MONTH,
    STRIKED_YEAR
ORDER BY NUM_KILLS DESC, TERRITORIAL_AUTHORITY, TOWN_CITY, STRIKED_DATE
