SELECT 
    GEO_LOCATION_ID,
    SUBURB_LOCALITY,
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY,     
    STRIKED_DATE,
    STRIKED_DAY,
    STRIKED_MONTH,
    STRIKED_YEAR,
    SUM(NUM_KILLS) AS NUM_KILLS
FROM {{ ref('nz_daily_kills') }} 
GROUP BY 
    GEO_LOCATION_ID,
    SUBURB_LOCALITY,
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY, 
    STRIKED_DATE,
    STRIKED_DAY,
    STRIKED_MONTH,
    STRIKED_YEAR
ORDER BY NUM_KILLS DESC, TERRITORIAL_AUTHORITY, SUBURB_LOCALITY, TOWN_CITY, STRIKED_DATE
