WITH trap_records AS (
    SELECT * FROM {{ ref('int_trap_details') }}
    WHERE ACTIVITY_TYPE = 'STRIKE'
),
daily_strikes AS (
    SELECT 
        LOCATION_ID, 
        TRAP_ID,
        ADDRESS_LATITUDE,
        ADDRESS_LONGITUDE,
        FULL_ADDRESS,
        FULL_ROAD_NAME,
        SUBURB_LOCALITY,
        TOWN_CITY,
        TERRITORIAL_AUTHORITY,    
        ACTIVITY_TYPE, 
        TO_CHAR(STRIKE_AT::TIMESTAMP, 'YYYY-MM-DD') STRIKED_DATE, 
        CREATED_BY
    FROM trap_records
)
SELECT 
    LOCATION_ID, 
    TRAP_ID,
    ADDRESS_LATITUDE,
    ADDRESS_LONGITUDE,
    FULL_ADDRESS,
    FULL_ROAD_NAME,
    SUBURB_LOCALITY,
    TOWN_CITY,
    TERRITORIAL_AUTHORITY,    
    ACTIVITY_TYPE, 
    STRIKED_DATE, 
    TO_CHAR(STRIKED_DATE::DATE, 'YYYY') STRIKED_YEAR,
    TO_CHAR(STRIKED_DATE::DATE, 'MM') STRIKED_MONTH,
    TO_CHAR(STRIKED_DATE::DATE, 'DD') STRIKED_DAY,
    COUNT(STRIKED_DATE) AS NUM_KILLS,
    CREATED_BY
FROM daily_strikes   
GROUP BY LOCATION_ID, 
    TRAP_ID,
    ADDRESS_LATITUDE,
    ADDRESS_LONGITUDE,
    FULL_ADDRESS,
    FULL_ROAD_NAME,
    SUBURB_LOCALITY,
    TOWN_CITY,
    TERRITORIAL_AUTHORITY,    
    ACTIVITY_TYPE,
    STRIKED_DATE,
    CREATED_BY
