{{
    config(materialized='view')
}}

WITH kills AS (
    SELECT 
        TO_CHAR(STRIKED_DATE::DATE, 'YYYY-MM') AS MONTH_YEAR,
        SUBURB_LOCALITY,
        TOWN_CITY,
        TERRITORIAL_AUTHORITY,
        NUM_KILLS,
        TRAP_ID,
        STRIKED_MONTH,
        STRIKED_YEAR
    FROM {{ ref('nz_daily_kills') }}
)
SELECT 
    MONTH_YEAR, 
    SUBURB_LOCALITY,
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY, 
    SUM(NUM_KILLS) AS NUM_KILLS,
    COUNT(DISTINCT TRAP_ID) AS NUM_TRAPS,
    STRIKED_MONTH,
    STRIKED_YEAR
FROM kills 
GROUP BY MONTH_YEAR, 
    SUBURB_LOCALITY,
    TOWN_CITY, 
    TERRITORIAL_AUTHORITY, 
    STRIKED_MONTH,
    STRIKED_YEAR
ORDER BY MONTH_YEAR DESC, NUM_KILLS DESC, TERRITORIAL_AUTHORITY, TOWN_CITY
